export default [
  'borderlands',
  'castlevania',
  'dark souls',
  'death stranding',
  'donkey kong',
  'grand theft auto',
  'half life',
  'klonoa',
  'metal gear solid',
  'metroid',
  'minecraft',
  'monkey island',
  'mortal kombat',
  'red dead redemption',
  'street fighter',
  'subnautica',
  'super mario',
  'tekken',
  'tetris',
  'the witcher',
];
